### PR TITLE
[HIPIFY][perl][fix] Do not hard-code path to perl

### PR DESCRIPTION
**Pull request by haampie**

### CODE REVIEW

**Review by emankov — CHANGES_REQUESTED** [review]
Looks ok to me, except regenerated `hipify-perl` should be added to the PR as well.

**Comment by haampie** [comment]
After running hipify-perl I got this difference too:

```
$ git add -p bin/
diff --git a/bin/hipify-perl b/bin/hipify-perl
index d155996..e6cae6c
--- a/bin/hipify-perl
+++ b/bin/hipify-perl
old mode 100755
```

I've kept the mode as it was

**Comment by emankov** [comment]
> old mode 100755
> new mode 100644
> I've kept the mode as it was

Yes, keep the old mode, as we need +x (executable) flag to run `hipify-perl`

**Review by emankov — APPROVED** [review]

**Comment by haampie** [comment]
Thanks!

**Pull request merged**
