### PR TITLE
[HIPIFY][SWDEV-437189][package][fix] Provide option to enable/disable `CPACK_SET_DESTDIR`

### PR DESCRIPTION
**Pull request by raramakr**
The variable is set as cache, so that user can override.

### CODE REVIEW

**Review by emankov — APPROVED** [review]
LGTM

**Comment by emankov** [comment]
Hello @frepaul,

Does this PR close SWDEV-437189 for HIPIFY tools? Could you please have a look at it, too? Thanks.

**Comment by raramakr** [comment]
> Hello @frepaul,
> 
> Does this PR close SWDEV-437189 for HIPIFY tools? Could you please have a look at it, too? Thanks.

While creating the hipify-clang package , the  CPACK_SET_DESTDIR will be set to OFF(from build scripts) to make it relocatable.

**Comment by emankov** [comment]
Hello @frepaul,

I also need your review and approval to merge this PR. Thanks.

**Review by frepaul — APPROVED** [review]

**Pull request merged**
