### PR TITLE
[HIPIFY] Add dependency on rocm-core

### PR DESCRIPTION
**Pull request by icarus-sparry**
The intention is to make all the rocm packages depend on rocm-core to
enable eveerything to be removed cleanly by just removing the
rocm-core package.

Signed-off-by: Icarus Sparry <icarus.sparry@amd.com>

### CODE REVIEW

**Comment by emankov** [comment]
HIPIFY package is a standalone tool independent from rocm-core.

**Comment by icarus-sparry** [comment]
The point of "rocm-core" is to provide an easy way to remove all of rocm. So the question is "Is hipify part of rocm?" If installing rocm is going to install hipify then removing rocm should remove hipify. I may not agree with it but the method that has been decided upon is to make all packages which make up rocm to depend on essentially a dummy package called "rocm-core" so removing rocm-core causes the package managers to remove all of rocm.

The alternative is to say hipify is not part of rocm.

**Comment by emankov** [comment]
> So the question is "Is hipify part of rocm?" 

Only theoretically. It is not installed with ROCm HIP; it has its own independent package. 
> If installing rocm is going to install hipify then removing rocm should remove hipify.

No, ROCm doesn't install HIPIFY, so it shouldn't remove it.

**Review by emankov — COMMENTED** [review]
This change is not needed.

**Review by emankov — APPROVED** [review]
LGTM, as we agreed on such a dependency for every component of HIP-SDK.

**Pull request merged**
